quiz = {

    //  Set our number counter to 120.
    var number = 120;
    var correct = 0;
    var incorrect = 0;
    var unanswered = 0;

    questions = {
        question1: "Who was the only non-member of the Beatles to receive a performance credit on a record?"
         question2: "John Lennon and Paul McCartney sang backing vocals on which Rolling Stones single?"
    }

    options = {
        option1: ["Eric Clapton", "Billy Preston", "Ravi Shankar", "Mick Jagger"],
        option2: ["I Wanna Be Your Man", "(I Can't Get No) Satisfaction", "We Love You", "Jumpin' Jack Flash"]

    }

    answers = {
        answer1: "Billy Preston",
        answer2: "We Love You"

    }
};
